---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=1in

title: "CV"
author: SHYLOCK MUYENGWA
#orcid: "orcid.org/0000-0002-9577-6885"
jobtitle: "Environmental Science, Evaluation and Social Research Design"
address: "15 Ridge Road Avondale. Harare. Zimbabwe"
fontawesome: yes
email: shylock.muyengwa@gmail.com 
github: shylock79
#phone: "+263779970322"
web: 'www.c4ierd.org'
updated: yes

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# EDUCATION

*University of Florida*, Ph.D. Interdisciplinary Ecology \hfill 2018

*University of Zimbabwe*, M.S. Social Ecology \hfill 2005

*University of Zimbabwe*, B.S. Psychology \hfill 2002

# SUMMARY 
> Dr. Muyengwa, has more than 10 years of relevant experience with rigorous quantitative research design and analysis/evaluation, survey design, as well as a breadth of experience in various sectors of agriculture, food security, youth employment and empowerment, governance, community based natural resources management, and livelihoods. Some of his skills include survey design and implementation, participatory methodologies, structured interviews, and focus group facilitation. Dr. Muyengwa has worked in Botswana, Namibia, Mozambique, South Africa, Zambia, and Zimbabwe 

# SELECTED CONSULTANCIES 

*Baseline Consultant Peace Parks Foundation* \hfill 2017(Dec)--2018(Aug)

> Conducted a livelihoods assessment survey in the Simalaha Conservancy in Zambia to prepare for the development of the Greater Kafue Widlife Area.   

*Baseline Consultant, Ministry of Environment- Government of Zimbabwe* \hfill 2016(Oct)--2018(Apr)


 
*Baseline Consultant Peace Parks Foundation* \hfill 2016(Jul)--2016(Aug)

> Collected situational and baseline data to inform the Greater Limpopo Trans-frontier Conservation Area’s Livelihoods Diversification Strategy. Drafted the Livelihoods Strategy document of the GLC

*Stakeholder Consultant, UNDP Zimbabwe* \hfill 2016(May)--2016(Jul)

*Social Impact Assessment Consultant, GEF Zambia* \hfill 2016(May)--2016(Jul)

> Conducted a Social Impact Assessment of the South Luangwa National Park. I led the collection of quantitative survey and analysis to understand the governance and livelihood impacts of protected areas. 

*Short term Research Design and Data Analysis Expert* \hfill  2014(Nov)-- 2015 (April)

 > Was hired as a consultant to lead the formulation and design of a national study on Citizen’s Perception of Access to Justice that is being implemented by CALR on behalf of the Ministry of Justice. 

*Lead Monitoring and Evaluation Expert (Africa Evaluation Association/ L’Assocation Africane d’Evalu)* \hfill Aug (2015)-- Dec(2015) 

 > I led the design of tools and the methodology for assessing the impact of African Capacity Building Capacity Foundation’s (ACBF) interventions in Africa from 1991-2014. My specific role was to formulate a  non-experimental evaluation design to assess ACBF’s impact over its 24 year life span in 45 African Countries.
 
*Local Capacity Builder (Monitoring and Evaluation), SNV- The Netherland Development Organization* \hfill  2013 (Oct)-- 2014(Feb)

 > I led the development of baseline strategy for  SNV’s Rural Agriculture Revitalization Program.  (RARP-CSF) sought to enhance household food security, generate employment and improve household income through the commercialization of smallholder farming across eight rural provinces of Zimbabwe. I collected and validated Monitoring and Evaluation data for Value Chain Financing, Matching Grants, Agrodealer Restocking, Contract Farming, and SME Support

*Team Leader (Monitoring and Evaluation), Clive and Associates* \hfill 2013 (Sept) --2013 (Nov)

 > I led a team reviewed PhytoTrade Africa's M&E system and provided strategic direction toward the client's 2014 fund-raising stratgey. In doing so, we developed indicators based on examples of best practice M&E and Marketing to revise and update PhytoTrade Africa's monitoring and evaluation system
 
 *National Biotrade Consutant, United Nations Conference on Trade and Development (UNCTAD)* \hfill 2013 (Oct) -- 2013 (Dec) 
 
 > Collected and collated BTIAS  data gathering sheets from serveral CSOs on for UNCTAD  and  PhytoTrade Africa for the years 2011 and  2012
Collaborated in the review of PhytoTrade Africa's environmental and  social  impact assessment indicators




# CONSULTING PROFILE

*Associate Professor, Mathematics, Vassar* \hfill 1931--1941

> Teach students about math, began career in programming and largely developed design and implementation of a computer compiler.
  
*Director, Navy Programming Languages Group* \hfill 1967--1977

> She developed validation software for COBOL and its compiler as part of a COBOL standardization program for the entire Navy. Hopper advocated for the Defense Department to replace large, centralized systems with networks of small, distributed computers. Any user on any computer node could access common databases located on the network. She developed the implementation of standards for testing computer systems and components, most significantly for early programming languages such as FORTRAN and COBOL. The Navy tests for conformance to these standards led to significant convergence among the programming language dialects of the major computer vendors. In the 1980s, these tests (and their official administration) were assumed by the National Bureau of Standards (NBS), known today as the National Institute of Standards and Technology (NIST). (Source: https://en.wikipedia.org/wiki/Grace_Hopper)

# PUBLICATIONS

## **Journal Articles**

Muyengwa, S. (2015). *Determinants of Individual Level Satisfaction with Community Based Natural Resources Management: A Case of Five Communities in Namibia*. Environments, 2(4), 608–623.
Muyengwa, S., & Child, B. (2017). *Re-assertion of Elite Control in Masoka’s Wildlife Program, Zimbabwe*. Journal of Sustainable Development, 10(6), p28. https://doi.org/10.5539/jsd.v10n6p28
Muyengwa, S., Child, B., & Lubilo, R. (2014). *Elite capture: A comparative Analysis of Meso Level Governance in Botswana, Namibia, Zambia, and Zimbabwe*. In B. Grenville & B. Child (Eds.), Adaptive Cross-scalar Governance of Natural Resources (1st ed., pp. 179–203). London, U.K.: Routledge.
Muyengwa, S., & Kangueehi, G. (2013). *Decentralized governance in Wuparo Conservancy, Caprivi, Namibia.* In C. M. Breen (Ed.), Community-Based Natural Resource Management in Southern Africa: An Introduction (pp. 205–214). United Kingdom: AuthorHouse.




# AWARDS

**1964**  *Society of Women Engineers Achievement Award*, the Society’s highest honor, “In recognition of her significant contributions to the burgeoning computer industry as an engineering manager and originator of automatic programming systems.”

**1969**  *Data Processing Management Association Man of the Year* (now called the Distinguished Information Sciences Award)

**1973** *Distinguished Fellow of the British Computer Society*. First American and the first woman of any nationality to be given award.

**1982** *American Association of University Women Achievement Award*

**1987** *Computer History Museum Fellow Award Recipient* First to receive this award, for contributions to the development of programming languages, for standardization efforts, and for lifelong naval service.

**1991**: *National Medal of Technology*

**1996**: *USS Hopper (DDG-70) was launched*. Nicknamed Amazing Grace, it is on a very short list of U.S. military vessels named after women.

**2009**: The Department of Energy's National Energy Research Scientific Computing Center named its flagship system "Hopper"

**2016**: Posthumously awarded a *Presidential Medal of Freedom* for her accomplishments in the field of computer science

